### ISSUE TITLE
Arrow function destructuring is not parsed

### ISSUE THREAD

**Issue by danielo515** [rajasegar/ast-builder#10]
First, thanks for this tool that heps a lot when it is time to write codemods.
I found one little annoyance, and it is that arrow function destructuring is not parsed. For example this:

```
const x = ({a}) => {a}
```

Is output as :

```
const x = () => {
    a;
};
```

I understand that this is not trivial because the API does not provide a way to use shorthand object properties, so you have to workaround like this:

```
        const a = j.objectProperty(x, x);
        a.shorthand = true;
```

The correct code for this would be:

```js
j.variableDeclaration("const", [
        j.variableDeclarator(
          j.identifier("x"),
          j.arrowFunctionExpression(
            [
              j.objectPattern([
                j.objectProperty(j.identifier("a"), j.identifier("a"))
              ])
            ],
            j.blockStatement([
              j.expressionStatement(j.identifier("a"))
            ])
          )
        )
      ]);
```

**Comment by danielo515** [comment]
Is this supposed to be deployed to the app?
The current outcome is even worse than the previous: 
![image](https://user-images.githubusercontent.com/2270425/101276324-51ba5280-37ac-11eb-93f9-81d6e03de13c.png)

**Comment by rajasegar** [comment]
@danielo515 Deployed the new changes just now and verified, please ensure your browser cache is cleared. Hope the issue is resolved.

**Comment by danielo515** [comment]
Hello @rajasegar , I tried it on an incognito window and I can see it is loading the new library version you updated (look at the bottom of the screenshot I just added), but it is still not working. Have you tried it? Is it working for you?

![image](https://user-images.githubusercontent.com/2270425/101333280-b80ba780-3876-11eb-976c-c829752fbb01.png)

**Comment by rajasegar** [comment]
@danielo515 Yes I checked the following ones are working
```js
const x = ({x}) => { x };
const x = ({x}) => x;
```
This pattern has not been handled yet with the expression statement, 
```js
({x}) => x
```
can you please give me a list of such patterns so that I can add tests for them and verify..

**Comment by danielo515** [comment]
Oh, you're right, that works nice. This works as well: 

```
setTimeout(({a}) => a, 300, {a:1})
```

the current limitation is not a problem for me.
